### ISSUE TITLE
Shopify layout changed

### ISSUE THREAD

**Issue by jtymoszczuk** [btcpayserver/btcpayserver-doc#1018]
Shopify recently changed their layout for creating custom apps. To reflect changes please update your instructions and screen shots at https://docs.btcpayserver.org/Shopify/#btcpay-server-and-shopify-integration

**Comment by pavlenex** [comment]
Hey @jtymoszczuk were you able to make it work? Indeed due to recent Shopify problems they've changed so many things. I'm not even sure that Shopify integration works as expected, would be good to get some feedback on what's changed/not working so that we can look into documenting it, perhaps a problem is beyond documentation.

**Comment by jtymoszczuk** [comment]
I'll have to show you how Shopify has changed. It is slightly different now.  Afk right for a while.  I'll see if I can get screenshot and document.

**Comment by pavlenex** [comment]
Integration got improved so docs should be accordingly https://github.com/btcpayserver/btcpayserver/pull/3501

**Comment by jtymoszczuk** [comment]
saw this. thank you

**Comment by pavlenex** [comment]
#1036
