### ISSUE TITLE
Create Zapier videos: how to setup your account + do some basic automations

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-doc#1061]
Can be 1 or multiple videos. I can record my screen, but a better voice over would be a good idea as I am not a native English speaker.

**Comment by woutersamaey** [comment]
Some templates of what you can do and eailiy setup are already on the Zapier page at https://zapier.com/apps/btcpay-server/integrations

Screenshot:
![image](https://user-images.githubusercontent.com/71019/160368084-b212c014-35b5-4473-a860-474c4aafd9f2.png)

**Comment by pavlenex** [comment]
Due to nature and flexibility of Zapier, these are best to be created in a short format addressing a specific problem so that could get better visibility. 
- [ ] Introductory video (connecting BTCPay & Zapier)
- [ ] How to receive emails on invoice status with Zapier and Gmail
- [ ] How to do add information to Google Sheets when BTCPay invoice is settled (Zapier)
- [ ] How to send messages on certain BTCPay invoice status on Slack

![072DDB29-57CB-4230-9D70-A625F629D576](https://user-images.githubusercontent.com/36959754/160368181-01b8fed0-737c-4921-abb6-44ef2bedd68d.png)

**Comment by Bangalisch** [comment]
Will take care of this in the next +/- 2 days

**Comment by Bangalisch** [comment]
With : https://github.com/btcpayserver/zapier/pull/8 we can close the first two on @pavlenex his list. 

Getting to the latter two :)
