### ISSUE TITLE
Write documentation for the upcoming backup and restore feature (PR 641)

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1116]
There is a massive PR being worked on by @dennisreimann concerning a new backup and restore feature.
As said on todays documentation call: We would like to help with writing to docs for that.

Questions for @dennisreimann:

* Do you have anything doc/text wise prepared that you want us to use?
* Are there plans to include the backup/restore feature in the GUI or will it stay a CLI only feature?

Here is the link to the PR for anyone interested in whats comming:
https://github.com/btcpayserver/btcpayserver-docker/pull/641

**Comment by dennisreimann** [comment]
Hey, that sounds great and your help is appreciated :)

>  Do you have anything doc/text wise prepared that you want us to use?

Not yet, just the basics outlined in the PR description and comments. I think those things should be covered:

- How does the backup work? (covers `btcpay-backup.sh`)
- What does the backup include?
- What needs to be considered and what isn't covered by the backup?
- How does the restore work? (covers `btcpay-restore.sh`)
- What are the options? (e.g. `BTCPAY_BACKUP_PASSPHRASE`)

Additionally I can also provide examples for a cronjob that runs the backup nightly

> Are there plans to include the backup/restore feature in the GUI or will it stay a CLI only feature?

As a first step I'd say we should keep it CLI-only and ensure it is solid. In general I think we should automate it as much as possible and integrate it into the Docker deployment, so that the user doesn't have to trigger the backup manually.

**Comment by Bangalisch** [comment]
i'll start working on a draft

**Comment by dennisreimann** [comment]
Thanks! Maybe we can encourage more people to test it if there are docs already. 😉
