### ISSUE TITLE
YouTube Video Playback broken in many browsers

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1264]
When trying to playback a youtube video in our docs, I get the following error:

![grafik](https://user-images.githubusercontent.com/1374810/231973482-cf679ace-5bd8-493d-962c-8d58f6f926af.png)

@pavlenex recommended bumping something, as sv2 also uses vuepress and their video playback still works.

Maybe @dennisreimann has an idea?

All Browsers tested with where affected:
- Chrome on Windows PC and Android
- Firefox on Windows Desktop and Android Mobile Version
- iOS Browsers also seem affected.

**Comment by dennisreimann** [comment]
Thanks for reporting, fixed!

**Comment by Bangalisch** [comment]
> Thanks for reporting, fixed!

Yooo

Just checked the solution and was like why take out all the alt text. I don't know if this is an actual solution. 
Searched further to find the actual moment this gone wrong and found a little thing with prettier 3 weeks ago. 
Running this changed all the "" into '' or from double to single quotes. The reason why the last video https://github.com/btcpayserver/btcpayserver-doc/pull/1255/files  worked was due to me doing them with the "". 

Just also tested this out with a PR (closed again by now to not have it merged). 

This was introduced due to using Prettier and this changed all the quotes..
https://github.com/btcpayserver/btcpayserver-doc/blame/ccf298a808b8564fce0d0e28e14198f7f30268ce/docs/Guide.md

**Comment by dennisreimann** [comment]
@bas I fixed it already, but the alt text shouldn't appear there in the first place — so this was basically wrong all the time, but somehow it worked while using `"` instead of `'`. However, the solution is to completely remove the alt text from the URL part of the links.

**Comment by ndeet** [comment]
@Bas02 @dennisreimann as discussed yesterday I added a markdown-it plugin that adjusts the parser to use the alt tags as title tags, see above linked PR. 

According to markdown spec the title needs to be in double quotes, so the prettier [commit](https://github.com/btcpayserver/btcpayserver-doc/commit/b1432054e147836d7286e1bae2f98e62f2752363) seems to have broken it as suggested by @Bas02 Maybe there is a way to avoid prettier to doing that, will also have a look at this.

**Comment by ndeet** [comment]
I checked the prettier single/double quote problem. The setting `singleQuote: true` is causing it obviously. What we could do is to have two separate prettier configs for js and json files and a different one with singleQuotes: false for .md files. But the problem then is that all the code samples in the .md files will get double quotes which is also kinda ugly :D

Ideally we would want prettier to have double quotes on markdown but not in mardown embedded code samples. Sounds like a n not so easy solution. Or the other way around, run pretter only on the embedded code samples and not the rest of the .md file. Even ChatGPT is a bit lost on this question :yum:

**Comment by dennisreimann** [comment]
@ndeet See the additions I've made in #1279 — I think this works fine as it is and we shouldn't use the extra titles feature anyways. If this still does not work, let's simply remove Prettier from the project and be done with it — I wouldn't want this to be something that we put more work into.
