### ISSUE TITLE
Document TOR support

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#198]
Not sure if this should be under features or just FAQ. Seems better suited for FAQ imo.
Some information available here https://medium.com/@BtcpayServer/about-tor-and-btcpay-server-2ec1e4bd5e51 and here https://twitter.com/BtcpayServer/status/1107591715685167104

Whoever is familiar with TOR and uses it with btcpay, feel free to document it.

**Comment by BobleChinois** [comment]
I just tried to activate tor, it was definitely very easy and it works well but I think it definitely needs some clarification about what it does and what it doesn't in the FAQ, because even after reading Nicolas' article on Medium I was a bit confused about it and thought it would force all bitcoind and lnd trafic through Tor. 
If nobody's already working on it I can make a pull request soon.

**Comment by pavlenex** [comment]
@BobleChinois Sure, go ahead, assigned this one to you. Ty.
