### ISSUE TITLE
Add Documention to Remove certain add-ons

### ISSUE THREAD

**Issue by Freefromchainz** [btcpayserver/btcpayserver-doc#214]
In the Process of trying to trim the fat on my server. Certain add-ons like libre patron that I'am not currently using i do not see documentation on how to remove them, as they maybe costing extra burst cpu usage on lunanode.

**Comment by pavlenex** [comment]
ping @JeffVandrewJr you may want to document how to comment out in LibrePatron docs as well :) I'll do it in FAQ.

**Comment by JeffVandrewJr** [comment]
I'm assuming we're talking about deactivating a previously activated instance, since if it's never active in the first place, this shouldn't be an issue. 

Rather than commenting out, I think it's cleaner to do the following:

`echo $BTCPAYGEN_ADDITIONAL_FRAGMENTS`

Then copy the entire string that pops up. 

Then do:

```
export BTCPAYGEN_ADDITIONAL_FRAGMENTS=<whole string other than opt-add-librepatron

. btcpaysetup.sh -i
```

Then you're permanently deactivated. 

If you want to take it a step further and destroy the data:

```
rm -r /var/lib/docker/volumes/librepatron
```

**Comment by Freefromchainz** [comment]
Thank you jeff!

**Comment by BobleChinois** [comment]
I just ran into this issue (needed to deactivate Tor to make a test), and figured how to do it thanks to this issue. Should I add it to the FAQ?

**Comment by pavlenex** [comment]
@BobleChinois sure, feel free to add instructions in FAQ on how to deactivate/remove the plugin(s).

**Comment by pavlenex** [comment]
[Added.](https://github.com/btcpayserver/btcpayserver-doc/pull/220)
