### ISSUE TITLE
Re-structure Connect a wallet section / Derivation scheme docs

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#418]
The ConnectWallet.md now contains a list of recommended wallets, however we recently added some changes and there are plenty of options for people to choose from.

BTCPay Vault should be our go-to recommendation for those who have a hardware wallet since it minimizes the changes for a mistake.

These options are available as of today:

![72886769-b4c50700-3d0a-11ea-9801-9fc02aed0725](https://user-images.githubusercontent.com/36959754/72984579-566c5700-3de4-11ea-8db1-e338c4c0b975.png)

Discussion on this subject is available in [#1263](https://github.com/btcpayserver/btcpayserver/issues/1263), so these changes can be applied after we decide on how we'll handle the wallet connection.

**Comment by pavlenex** [comment]
Vault.md should be added on to-do for this issue as well, since right now it's not linked on GitBook anywhere.

**Comment by britttttk** [comment]
Vault is in Wallet.md and has it's own doc Vault.md (Hardware Wallet Integration) so I believe the comment 
> since right now it's not linked on GitBook anywhere

is outdated. 

While we are waiting for the Issue 1263 mentioned above to be resolved, we can for now, at least work on adding a recommendation for using Vault in ConnectWallet.md as you suggested. But it's already mentioned in the wallet specific docs... so i'm not sure if it's redundant or if it should be mentioned because it allows users to use hardware wallets which we do not have listed in the External/Internal Recommended wallets section. 

@pavlenex is this actionable now or blocked by the derivation scheme ux changes?

**Comment by pavlenex** [comment]
Sorry @britttttk missed this one. I agree that we should probably work on that. That whole section is not good enough, we-need a restructure. I will try to suggest a new UI idea for [1263](https://github.com/btcpayserver/btcpayserver/issues/1263) that may help us structure existing docs better. External and internal wallets is a terrible way of communicating this, what the hell was I thinking there.

**Comment by pavlenex** [comment]
Well for now I consider this section re-structured. We can't do anything beyond this. This structure already has in mind the new possible derivation scheme that we ca re-visit.

![happy](https://user-images.githubusercontent.com/36959754/81976702-3e397580-9629-11ea-98a6-9f8d31130a5f.PNG)
