### ISSUE TITLE
Move documentation front-end from GitBook to vuepress

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#495]
Current documentation front-end is hosted by GitBook. While  this was fantastic and easy start for us which allowed us to have a quick nicely looking solution, the complexity of our documentation is growing. Unfortunately, the need for customization can't be done all via GitBook.

Here are current feature we're missing:
- Make a design consistent with our design-guidelines
- Multi-repository documentation

## Multi-repo documentation
The multi-repo docs would allow us to have docker, transmuter or any other repository presented on the front-end while on-the back-end their documentation stays in the respective repositories. This makes maintainance of documentation easier, since the changes are made on the back-end of respective repo. For example, our docker documentation on the front-end is very brief, where as btcpay-docker is one of most extensive documentations we have. With multi-repo access we'll be able to render btcpay-docker without having to maintain a page for it in the docs.

## Design consistency
Efforts to make BTCPay Server look like a coherent piece of software accross multiple platforms continues. We've already had people asking for for a dark mode of our docs, which with GitBook limitation is not possible.

Gitbook itself has advantages over VueJS for sure. They have an analytics and rating system, but to be honest we've never looked at that. Furthermore as a privacy orientated software, we don't really care about them. Perhaps a feedback system would be nice to have.

@dennisreimann will take a lead on this since he's helped Wasabi Documentation and has plenty of experience in this field. Of course, we will first test on forks to see if we can make it all work as we want.

If you have any suggestions please let us know. I'll leave it up to @dennisreimann to expand on other advantages that we get with vue.js.

For those interested into seeing vuepress in action here is a list of projects using it in different ways. 
We've been recomended Agora as well, but it has a markdown language of it's own which would require an insane amount of modifications on our end, which is not what we want.

**Comment by dennisreimann** [comment]
Alright, I've set up a [fork](https://github.com/dennisreimann/btcpayserver-doc/tree/vuepress) (see the **vuepress branch**) and [deployment](http://btcpaydocs.uix.space/), so that we can test everything and build a proof of concept for the steps involved:

- [x] General VuePress setup and docs migration
- [ ] Multi-repo setup
  - [ ] Integration of and build for repos other than doc
  - [ ] Build triggers for the doc repo whenever a dependecy repo changes (or better yet, the docs in that repo)
- [ ] Design adjustments
- [ ] Migrate complete navigation and eventually adjust the structure (e.g. using subfolders)

One more thing I'd advise: Let's [apply for Algolia for Open Source](https://www.algolia.com/for-open-source/). Their search is great and easy to integrate into VuePress. From my experience it takes a while until they approve open source accounts, so let's just do that right away. Ok, @pavlenex?

Note: Right now only part of the navigation is converted, but what's there works for getting a feel for the basics. The configuration and public files (like images) are in the [docs/.vuepress](https://github.com/dennisreimann/btcpayserver-doc/tree/vuepress/docs/.vuepress) directory and here are the [details of how to configure the site](https://vuepress.vuejs.org/config/#basic-config).

Feedback welcome!

**Comment by dennisreimann** [comment]
[Multi-repo build](https://github.com/dennisreimann/btcpayserver-doc/runs/634090309) works and @Kukks [set up a trigger for the btcTransmuter build](https://app.circleci.com/pipelines/github/btcpayserver/btcTransmuter/318/workflows/01540587-aa48-4bf2-9fb1-e55301ab2c36/jobs/533/steps) that we are currently trying to get to kick off the main build too.

The [Docker](https://btcpaydocs.uix.space/Docker/) and [Transmuter](https://btcpaydocs.uix.space/Transmuter/) docs appear last in the nav on the left right now -> [Docs](https://btcpaydocs.uix.space/).

**Comment by pavlenex** [comment]
That's so freaking cool guys, fantastic work so far! I applied or Algolia that one should be done soonish.

**Comment by dennisreimann** [comment]
Light dark theme are integrated, need to add the theme switch to make it an explicit choice next :)

**Comment by dennisreimann** [comment]
Added the theme switch (OMG is this nice 😍) and improved the video and image integration 👍

**Comment by dennisreimann** [comment]
Videos are now lazy loaded on demand and played inline, which feels very nice imho.

![](http://g.recordit.co/4c6MWti5wl.gif)

**Comment by dennisreimann** [comment]
And we have [custom blocks](https://github.com/dennisreimann/btcpayserver-doc/blame/master/docs/ManualDeploymentExtended.md#L5) like this one here with `danger`, `warning`, and `tip`:

<img width="702" alt="warning" src="https://user-images.githubusercontent.com/886/81018331-940d6100-8e64-11ea-866d-83b5a8bf6166.png">

Reference for [custom containers](https://vuepress.vuejs.org/guide/markdown.html#custom-containers).

**Comment by pavlenex** [comment]
Thanks for making the videos load properly. It's been a nightmare to maintain and a terrible UX so far. Great work Dennis.

**Comment by dennisreimann** [comment]
Updated the Algolia config and now the basic integration work. Nevertheless they [configured](https://github.com/algolia/docsearch-configs/blob/master/configs/btcpayserver.json) it for the current docs.btcpayserver.org, that's why we should also send in a PR to update the config once we've merged and deployed the new version with the correct selectors. I've added a TODO for that.

@pavlenex Let's figure out the new structure next. This one is almost ready to go 🤟

**Comment by pavlenex** [comment]
With #501 in mind, I've been thinking quite a bit, and here's what I suggest. If something is unclear, let me know so I can elaborate on why something is structured that way.

# Documentation

## User Docs
## Introduction
- Introduction
- Features
- How it works 

### Basics
- Use Case
- BTCPay Server vs others 
- Try it Out

### Deployment
- Choosing a deployment method
- Third-party hosting
- Docker
-- Docker Plugins
--- Tranmsuter
--- PiHole
 -- Web Deployment
 --- Configurator
 --- LunaNode
-- Azure Deployment
--- Azure pennypitnching gude
-- Google Cloud Deployment
- Manual deployment
-- Manual deployment extended
-- Hardware deployment
--- Raspberry Pi Deployment
---- Raspberry Pi 3 Deployment
---- Raspberry Pi 4 Deployment
--- Advanced Hardware Deployment
----Dynamic DNS
----Reverse SSH Tunnel

### Getting Started
- (1) Register account
- (2) Create a store
- (3) Connect a wallet
 -- Connect  a hardware wallet (Vault.md)
 --- Ledger
 --- ColdCard
-- Connect a software wallet
--- Electrum
--- Wasabi
-- Create a wallet
--- Hot wallet
- (4) What's Next?

### Features
- Apps
- Wallet
- Invoices
- Payment Requests
- Lightning Network
- PayJoin (P2EP)
-- Payjoin Specification

### Integrations
-WooCommerce
-Drupal
-Magento
-PrestaShop
-Custom Integration
### Support and community
-FAQ and common issues
--FAQ Table of Contents
--General FAQ
--Deployment FAQ
--Synchronization FAQ
--Integrations FAQ
--Server Settings FAQ
--Stores FAQ
--Wallet FAQ
--Apps FAQ
--Lightning Network FAQ
--Altcoins FAQ
-Troubleshooting an issue
-Support
-Contribute
-Translate
-Community

## Dev Docs
- API Docs
-- New API
-- Legacy API (BitPay)
- Clients 
-Development
-Architecture
-Developing Locally
-How to add an Altcoin
-Customizing Themes
-FAQ and common issues

## A few notes:
- It's not yet determine how we'll separate user and dev docs, most likely on the docs.btcpayserver.org we'll need to do different CTA discussion [here](https://github.com/btcpayserver/btcpayserver-doc/issues/501)
- While I am very proud of what I did with ` Connect a wallet` section, in reality it, for a full effect, derivation scheme [re-structure in UI of BTCPay Server itself ](https://github.com/btcpayserver/btcpayserver/issues/1263)is needed.
- Dev docs section is not at all final, it needs to be filled with docs from different clients we have
- I was not sure if "Integrations" is user-doc or dev doc. I had same dilema for "deployment" but kinda felt it's user-doc, though some deployment methods may more be dev-docs.
- Deployment section was a mess due to all of deployment methods being docker. 
- Added Docker plugins section where we can document third-party plugins like PiHole, Tranmsuter, etc @dennisreimann is is realistic to expect people that add plugins will allows us to automate deployments from their repo? How would that work?


Feedback is welcome of course, this is still not perfect, and needs actual docs re-works for it to take full effect.

**Comment by pavlenex** [comment]
@dennisreimann Just a side note, @dennisreimann I'm personally not a fan of `content:not(.custom) {
    max-width: 740px;` it looks like a bit too much unused space. Not an expert on this, but I find existing docs easier to focus. Would be cool if we can get different iteration on that layout.

**Comment by Kukks** [comment]
From a quick glance it looks good from my end

**Comment by dennisreimann** [comment]
> Added Docker plugins section where we can document third-party plugins like PiHole, Tranmsuter, etc @dennisreimann is is realistic to expect people that add plugins will allows us to automate deployments from their repo? How would that work?

We can pull and integrate their docs, but I would refrain from changes in their repos/docs triggering an update of our docs. The main reason for that is we'd need to provide a personal access token from an account of ours that has the permission to trigger the build. The permissions on GH aren't fine grained enough though, so that we'd hand out all kinds of permissions along with that … 
Anyways, I don't think that this is a show stopper for the idea, beecause our docs should be building frequently (we could also set up a scheduled build like once daily, even though nothing changed) and worst case is that they'd have to request a new build once their docs changed.

**Comment by pavlenex** [comment]
Feedback from 13" MacAir now :)
Tested on Firefox, Safari and Chrome.

@dennisreimann I noticed a few things:
1. The light-mode background is grey. Our current is white and looks better and easier to read. Any particular reason why you went with gray here?
**Demo docs**
![Screenshot 2020-05-06 at 22 44 23](https://user-images.githubusercontent.com/36959754/81226442-26d80800-8feb-11ea-86e7-c0ae10042194.png)

**Current docs**
![Screenshot 2020-05-06 at 22 25 21](https://user-images.githubusercontent.com/36959754/81225107-fe4f0e80-8fe8-11ea-9a77-1762b4f57c86.png)
2. Payjoin link has no nesting and leads to a broken url
3. I still feel the main content is congested. On 13"`.theme-default-content:not(.custom) {
    max-width: 900px;` did this which I personally found easier to read (unsure about what others think)
With 900px
![Screenshot 2020-05-06 at 22 47 01](https://user-images.githubusercontent.com/36959754/81226730-9948e800-8feb-11ea-8e96-18be18db4cf5.png)

Current 
![Screenshot 2020-05-06 at 22 47 12](https://user-images.githubusercontent.com/36959754/81226704-8d5d2600-8feb-11ea-90b5-28fd0350274b.png)

4. We need to add walkthrough.md (I forgot it in the above proposal), unsure where to put it, maybe just add in basics for now

5. Do you think we should nest all sub-FAQ things, looks a bit too much, doesn't it?

6. Leaving this as a reminder - don't deploy until we fix development section and determine what goes there

**Comment by dennisreimann** [comment]
> The light-mode background is grey. Our current is white and looks better and easier to read. Any particular reason why you went with gray here?

That's to match the same look we've got in the main app interface, website, directory etc.
Here's what it looks like plain white:

![white](https://user-images.githubusercontent.com/886/81269403-8b29b480-9049-11ea-9165-6bf5426416ae.png)

> 2. Payjoin link has no nesting and leads to a broken url

For me both of that works – can you try a hard refresh circumventing the cache?

> 3. I still feel the main content is congested. On 13".theme-default-content:not(.custom) { max-width: 900px; did this which I personally found easier to read (unsure about what others think)

imho 900 is too wide and the lines grow too long, which makes it harder to read. Tried a bit and would not recommend a value bigger than 800.

> We need to add walkthrough.md (I forgot it in the above proposal), unsure where to put it, maybe just add in basics for now

Will re-add it to the Basics section with the next commit.

> Do you think we should nest all sub-FAQ things, looks a bit too much, doesn't it?

I think the FAQ could get an own main category (like *Features* or *Integrations*) so that we move it out of *Support and Community*. 

> Nesting icons don't exist in the light-mode.

They are too light, will make them more prominent in both modes.

**Comment by pavlenex** [comment]
I am quite certain some of the issues I pointed out are due to different monitors and color calibrations, that said:

>  Here's what it looks like plain white:

@dennisreimann Can you check this on your Mac as well? On desktop monitor the gray does not look that weird and width there is good. I am thinking we should slightly adjust the width for 13" but please check the colors on your end. When I look it on a smaller screen, the gray makes it quite distracting to read, though this is a personal taste. Unlike interface docs is something a person has to focus quite much to read and I think it's more natural on the white, though we can keep the sidebar grey?

> I think the FAQ could get an own main category

The FAQ need to undergo a huge cleanup #504 so I'd keep them as they are now nested, until we figure out the structure there, it's a bit messy rn.

**Comment by pavlenex** [comment]
Just noticed we have two GitHubs, we can use icons for twitter and GH? (I'd leave gh pointing to main repo
![github](https://user-images.githubusercontent.com/36959754/81272595-f4abc200-904d-11ea-97da-c63738200d92.PNG)

**Comment by Zaxounette** [comment]
Pavlenex asked for more eyes for feedback, so here is my tiny contribution =)

### Links (broken, misdirects and such)

- Every single "edit page" link in the very bottom is broken and links to the "to-be-old" github md file, but that might be expected.
- https://btcpaydocs.uix.space/Walkthrough/#stores
First §, link "integrations" is broken and directs to the github docs instead of the vuepress docs.
- https://btcpaydocs.uix.space/Walkthrough/#wallets
Last link before "invoices", named "Wallet FAQ" gives a 404.
- https://btcpaydocs.uix.space/BTCPayVsOthers/#can-t-find-this-information-for-other-payment-processors
Very last link, named "Official documentation" redirects to github version, not vuepress one. 
On top of that, a link to the docs from the docs might be redundant.
- https://btcpaydocs.uix.space/TryItOut/#create-your-first-invoice
Last link, named "What's next" directs to github version.
- https://btcpaydocs.uix.space/HardwareDeployment/
Step 3, link for Ubuntu 18.04 image gives a 404.
- _Same page as above_, step 8 and step 10 both have links to download Putty, but different ones. 
- https://btcpaydocs.uix.space/Transmuter/#how-do-i-deploy
Very first link ("dockerized install method") directs to Github version of the docs instead of vuepress.
- https://btcpaydocs.uix.space/Transmuter/#what-preset-recipes-are-provided
Link ("BTCPay Email Receipts") is broken, gives a 404.
- https://btcpaydocs.uix.space/Transmuter/EmailReceiptsPreset/#transmuter-email-receipts-setup
First link ("SMTP Server setup") links to github page of FAQ-ServerSettings.md. Said file is missing on the vuepress version.
- _Same page as above_, link "Paid or Confirmed" links to github page of invoices.md instead of https://btcpaydocs.uix.space/Invoices/

### Menu item changes
- https://btcpaydocs.uix.space/LunaNodeWebDeployment/ 
Section "Web Deployment" in the sidebar could be renamed "Lunanode Deployment" or something of the sorts, to stay consistent with other sidebar titles that are named after the respective website where you can deploy from.
- https://btcpaydocs.uix.space/ChangeDomain/#setting-up-your-dns-record
This page is placed in Deployment > Azure deployment, and could go elsewhere in the sidebar, as it doesn't only concerne Azure deployments.
- https://btcpaydocs.uix.space/DynamicDNS/ and https://btcpaydocs.uix.space/ReverseSSHtunnel/
Pages are under "Hardware Deployment" on the sidebar menu but don't specifically concerne hardware deployments ? 
Move "Advanced Deployment" with other deployments under "Deployment" and rename to something like "Advanced tools for deployment" to suggest it's not actual deployments but tools that help in doing so?
- https://btcpaydocs.uix.space/RaspberryPiDeployment/
Move "RaspberryPi Deployment" (and child menus) under "Hardware Deployment" since RaspPi's are hardware ?

### Miscellaneous 
- https://btcpaydocs.uix.space/LunaNodeWebDeployment/#_1-create-the-account-and-add-credits
Link named "see this article" directs to the Lunanode setup guide on bitcoinshirt.co . Said article maybe could be ported inside the documentation and freshened-up ?
- A number of non-broken links direct purposely to other websites/guides that could be ported directly into the documentation. I feel like this would lessen possible confusions ?


I have seen no UX/UI or broken by code issues for the time being.

That's all I have for tonight. Got up to the end of the "deployment" menu with this.

**Comment by dennisreimann** [comment]
Hey @Zaxounette, thanks for the valuable feedback! The links are fixed, for the "Menu item changes" I'm awaiting @pavlenex' feedback on how to proceed.

**Comment by pavlenex** [comment]
Thanks Dennis for great work and @Zaxounette for in-depth feedback. I really did my best to break stuff around, but imo this thing is very close to being ready for merging.

Our priority right now is to make sure docs are displayed properly and it's critical that no internal links and absolutely critical that no external links are broken. It seems that @dennisreimann has taken care of that. 

My questions:
- Once merged, will the links be properly 301 redirected to a new link @dennisreimann? For example https://btcpaydocs.uix.space/getting-started/connectwallet/ledgerwallet re-directs excellenty, I just want to make sure it's properly handled for search bots as well as humans. 
- I still don't understand why VuePress doesn't allow a hover over a link that's not a page itself. Makes no sense not to have an indicator that `Docker Plugins` is not clickable. (For example `Connect a hardware wallet ` has it. But then `Connect a software wallet ` doesn't.
Priority (crucial before we merge)

## To Do

### Critical
- https://btcpaydocs.uix.space/Features/ and https://docs.btcpayserver.org/features/ don't behave in a same way. Lots of our external links have just /features.
-

### Not a prioriry
Not a priority but would be nice before we merge
-  onClick Image Zoom Effect like we do on old docs


### After the merge
Here are just minor annoyances I noticed that are unrelated to Dennis work but once merged we can tackle them, it's good to list things as you test.
- Docs readme should have a brief intro, point to the front-end and tackle how to contribute together with some styling guides and how to apply them.
- Re-phrase `Please check out our official website , our complete documentation and FAQ for more details.`
- Docker deployment page replaced with automated multi repo readme in btcpayserver-docker.

**Comment by Zaxounette** [comment]
Before merging, i'll do the same checks I did previously up to "deployment" for the rest of the docs, except maybe the FAQ pages, since i'm working on them (i'll just check for broken links on the FAQ).

I'll work on that tomorrow evening.

**Comment by dennisreimann** [comment]
First the bad news: I haven't found a way to do proper 301 redirects on GitHub Pages, yet. From my research this isn't possible on an HTTP level, we can just approach this with a hacked 404 page, but that won't make search engines happy. From what I see we'd havee to add a custom frontend proxy for that.

On a more positive note though: 

- Added image zoom
- Added hover for the collapsible categories that aren't pages themselves
- Added aliases for the categories to their first subpage

**Comment by dennisreimann** [comment]
As GitHub Pages does not support 301 redirects out of the box, I've generated custom HTML pages that contain a redirect via the `<meta http-equiv="refresh">` tag. According to [some resources](http://sebastians-pamphlets.com/google-and-yahoo-treat-undelayed-meta-refresh-as-301-redirect/) this should be handled equivalently by most search engines.

Firefox and Chrome also report these redirects as 301 in the network inspector, that's what I tried to confirm the desired behaviour. I think this is as far as we can get with GH Pages.

**Comment by pavlenex** [comment]
Yup, was reading on that as well this morning. In my experience if it's 301 in the network inspector it should be enough. I assume we're ready for a PR.

**Comment by Zaxounette** [comment]
@pavlenex @dennisreimann 

Alright ! Second batch of review is in ! 
Mainly focused on broken links.


### Links (broken, misdirects and such)
- https://btcpaydocs.uix.space/ElectrumWallet/
Third link "Electrum Personnal Server (EPS) links to github version instead of vuepress corresponding page (https://btcpaydocs.uix.space/ElectrumPersonalServer/)
- https://btcpaydocs.uix.space/WhatsNext/#connecting-your-btcpay-store-to-your-e-commerce-platform
Magento link should link here: https://btcpaydocs.uix.space/Magento/
Prestashop link should link here: https://btcpaydocs.uix.space/PrestaShop/
- https://btcpaydocs.uix.space/LightningNetwork/#choosing-the-lightning-network-implementation
Link "web-interface installations" should link to https://btcpaydocs.uix.space/LunaNodeWebDeployment/
- https://btcpaydocs.uix.space/WooCommerce/#_2-1-self-hosted-btcpay
Link "launch a self-hosted BTCPay" should link to https://btcpaydocs.uix.space/Deployment/
- https://btcpaydocs.uix.space/PrestaShop/#contribute
Link "Github issues" gives a 404
- https://btcpaydocs.uix.space/Architecture/#architecture
BOTH links "Web-Interface LunaNode deployment" and "Web-Interface deployment" (at the near bottom) should link to https://btcpaydocs.uix.space/LunaNodeWebDeployment/

### Menu item changes
- https://btcpaydocs.uix.space/Vault/ 
Explains what the BTCPay Server Vault is, but is staged in the "Connect to Hardware Wallet" Menu Item instead of it's own menu item.

### Miscellaneous
- https://btcpaydocs.uix.space/ElectrumX/#steps-to-enable-electrumx-server-in-btcpay
Sentence with link "In a future release we will integrate EPS into BTCPay [...] personal wallet" can be deleted, since PR has been merged.

**Comment by pavlenex** [comment]
Ok, so nothing critical left over as this can all be done after the merge. Ready when you are @dennisreimann.

**Comment by dennisreimann** [comment]
Done, except for the **Menu item changes** as I think we should postpone these to upcoming restructurings after the merge.
