### ISSUE TITLE
Expand "Custom Integration"

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-doc#542]
We should split Custom Integration into 4 pages:
* BitPay compatible invoice API
* * Available Libraries 
* Displaying a BTCPay invoice in a modal/dialog
* GreenField API
* * Available Libraries

**Comment by Zaxounette** [comment]
Kukks, can you expand on this ?

**Comment by pavlenex** [comment]
I think the goal of this was to prominently display the API and help distinguish the BitPay vs Greenfield as well as prominently display libraries.

I'll close this one because:
- We now distinguish Greenfield and BitPay's in:
   -  Docs FAQ
   - Readme of the main repo
   - Docs

We should probably at some point open up a new issue once we have libraries ready to see how we can distiquish those, this is added to the roadmap.
