### ISSUE TITLE
Multiple broken links in docker.md

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#566]
Multiple (like a whooooooooole lot) of broken links in docker.md

For example:
https://docs.btcpayserver.org/Docker/#generated-docker-compose

Every single `opt-XYZ` internal link is broken. 
Some external links are also broken.

Recommend reviewing the entire file.

**Comment by pavlenex** [comment]
These links aren't broken on GitHub, so it's a bug in our vuepress. Ping @dennisreimann

**Comment by dennisreimann** [comment]
These are relative links inside the repo, which makes it hard to handle: I think we can fix it by trying to replace those cases (like we do [here using `sed`](https://github.com/btcpayserver/btcpayserver-doc/blob/master/setup-deps.sh#L12)), but it might turn out to be error-prone as there are many assumptions we have to use. One of those assumptions would be to prefix these relative links with `GITHUB_URL_OF_REPO/blob/master/`.

I need to play around with it a bit and see if there are cases that don't allow for a straight forward solution. Otherwise it'd be best to turn them into absolute links to the desired URL in the docs.

**Comment by pavlenex** [comment]
absolute links for external repos sounds easier than to hack-around imo.

**Comment by dennisreimann** [comment]
Let me have a try at this, but I‘m with you on not using something that might be brittle.

**Comment by dennisreimann** [comment]
Think I've found a good way to approach and fix this in #568. Please verify the PR :)
