### ISSUE TITLE
Add "Not satisfied? Tell us why" to docs pages

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#596]
Add at the end of each doc page, add a "Not satisfied? Tell us why!" link which takes you to a new btcpayserver-doc repo github issue to write comments. @Kukks is this what you were thinking? 

I think this could be good. We don't really get much feedback on the docs other than broken links at the moment. Although the chat button is quite clear, I don't know if users will join the chat if they don't like the docs (if something was hard to find for example).

**Comment by britttttk** [comment]
Only thing that probably complicates this is that most of these users probably don't have a github account so they will see registration screen when they open this link..

**Comment by Zaxounette** [comment]
I had an idea to tackle this issue, with a final look being something of the sorts:

![Screenshot_72](https://user-images.githubusercontent.com/51208677/87571067-c68bd380-c6c9-11ea-9896-2a9643bd8361.png)

The "Edit this page" link is already in every single page of the docs.
I simply wanted to add 1 or more links in the footer.

After having asked Dennis, it turns out said footer is hard coded in the Vuepress theme (so not in any of this repository's files) and it would require skills above mine for the time being, so I decided to share the idea nontheless, if anyone feels it fits the issue and want's to implement it.

**Comment by dennisreimann** [comment]
Summarizing what we talked about in the chat: From what i can see it'd be adding the `docs/.vuepress/theme/components/PageEdit.vue` file as an [override](https://vuepress.vuejs.org/theme/inheritance.html#override-components) based on the [PageEdit.vue from default-theme](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/PageEdit.vue) and then adjusting it to fit our needs.
