### ISSUE TITLE
Document Notifications?

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#606]
Unsure if we need a doc for notifications? 
It'll probably become extensive feature once we add all the possibilities and and user-preference.
Not sure where to put it, under features?

**Comment by Zaxounette** [comment]
I wouldn't document notifications until the preference feature for them comes in.
Simply because a notification is a really common thing now. You find them in every app you have, every browser and even the most clueless person known what a notification is.

Just to avoid confusion (and unnecessary questions), maybe the only thing to add is in the BTCPay Server instance, in the notifications page, something saying that preferences aren't yet implemented ?
My2cents

**Comment by pavlenex** [comment]
Fair. I didn't want to document what notifications are, rather have a list of what's available, but makes sense to wait I guess until we add more of them and preferences.

**Comment by britttttk** [comment]
I think we should document it.

**Comment by britttttk** [comment]
It is also already partially documented in Pull Payments doc.

**Comment by pavlenex** [comment]
Alright then, I'll go ahead and close this one as there is a consensus not to do it.

**Comment by britttttk** [comment]
Actually from looking at existing docs, I think it should be documented in [Walkthrough.md](https://docs.btcpayserver.org/Walkthrough/) because it's an icon in the home view. Also need to update the home view image.

**Comment by pavlenex** [comment]
#647
