### ISSUE TITLE
Scrolling issue in # titles

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#614]
Hello folks ! 

There was an issue reported on the Mattermost [here](https://chat.btcpayserver.org/btcpayserver/pl/ucyqxppqujbdtqag3wu3uxhs8h) concerning the titles embedded with the # character. 
These titles don't scroll to the appropriate section.
The issue seems to appear in the following situations:
- When we click on a link that directs to the directory from outside of it (not an internal link)
- When a link to the directory contains the # embedded title

**Steps to reproduce:
Issue N°1:**
1°) Click on this link: https://docs.btcpayserver.org/FAQ/FAQ-General/#how-can-i-contribute-to-btcpay
2°) Get sent to the very top of the page containing the title

**Issue N°2:**
3°) When at 2°), click the `How to contribute to BTCPay` title
4°) Get nothing out of it, no scroll.

Issue verified in Chrome and Firefox, both up to date.

**Comment by dennisreimann** [comment]
Hmm, [it works using Firefox](https://recordit.co/ppNhXmvlB6) – but not in Chrome and Safari. 
The issue seems to be with WebKit-based browser on page load. It works fine once the page is ready though.

It's a static HTML page that contains the correct anchor, which you can see using 
`view-source:https://docs.btcpayserver.org/FAQ/FAQ-General/`

So in general this is supposed to work. I also checked the Vuepress docs site, where it works in all browsers. So I guess this could be related to some customization, maybe in [this file](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/.vuepress/enhanceApp.js).

Will investigate. 🕵️‍♂️
