### ISSUE TITLE
Documentation for shopify integration

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver-doc#668]
https://github.com/btcpayserver/btcpayserver/pull/1830

**Comment by britttttk** [comment]
@pavlenex anything else needed for this?

**Comment by Zaxounette** [comment]
One thing I discovered this afternoon is that the integration doesn't work for subscription items in shops. Only for single or bulk items.
This is apparently due to Shopify limitation, and neither the merchant nor us can do anything about it.

This info is currently missing in the doc (or at least I didn't see it).
