### ISSUE TITLE
Incorrect information about LND's pruning support

### ISSUE THREAD

**Issue by guggero** [btcpayserver/btcpayserver-doc#716]
The documentation contains the sentence "Both LND and c-lightning support pruning" in https://docs.btcpayserver.org/FAQ/FAQ-LightningNetwork/#can-i-use-a-pruned-node-with-ln-in-btcpay.

Unfortunately that is **not** (yet) true for `lnd`: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#pruned-bitcoind-node

We are working on [1st class pruned node support](https://github.com/lightningnetwork/lnd/issues/2997). But currently if the storage size for the pruned node is chosen too small, this can lead to `lnd` not being able to verify all channels (especially old channels that were opened in the beginning of the mainnet network) and causing strange behavior and potential performance issues (caused by `lnd` to fetch a non-existing block over and over again).

**Comment by gkrizek** [comment]
Also, In the docker deployment repo it doesn't explicitly state one way or the other about LND's support of pruning. However, since it does like the pruning options and LND as an option it might be worthwhile to explicitly state that it is not supported
https://github.com/btcpayserver/btcpayserver-docker#generated-docker-compose

**Comment by pavlenex** [comment]
I've been running a pruned LND nodes for on and off ~2 years.

> But currently if the storage size for the pruned node is chosen too small, this can lead to lnd not being able to verify all channels

I assume you mean [this](https://github.com/btcpayserver/btcpayserver-docker#generated-docker-compose) 

```
opt-save-storage will keep around 1 year of blocks (prune BTC for 100 GB)
opt-save-storage-s will keep around 6 months of blocks (prune BTC for 50 GB)
opt-save-storage-xs will keep around 3 months of blocks (prune BTC for 25 GB)
opt-save-storage-xxs will keep around 2 weeks of blocks (prune BTC for 5 GB) (lightning not supported)
```

**Comment by guggero** [comment]
What size did you use, @pavlenex? I'm really surprised you never ran into issues. Are you sure you don't see strange errors and/or high load on your system?

**Comment by pavlenex** [comment]
I've always used `opt-save-storage-s `. I think majority of people use that options. I've ran into quite a few issues, but i just re-deploy and continue my life 😄. 

People indeed report they have high load CPU problems with LND. Sometimes it happens as soon as they deploy nodes and sometimes after a while.

**Comment by Zaxounette** [comment]
I've had an instance deployed on Lunanode for a year and a half now, with LND from the start. `opt-save-storage-s` also. Have had one issue with LND stopping for an unknown reason. A simple VM restart fixed it.
Other than that, works perfectly with the 50 GB pruning.

**Comment by gkrizek** [comment]
If you guys would like to run LND in an unsupported fashion that's up to you, but the docs should definitely be updated to accurately reflect what's supported by LND.

**Comment by pavlenex** [comment]
@gkrizek So what do you suggest? 99% of btcpay instances use pruned nodes. imo modifying docs wouldn't have any impact except "we told you so". If that's the goal okay, otherwise we can just discontinue LND in pruned node?

**Comment by gkrizek** [comment]
I think modifying the docs would deter people from unknowingly running LND in an unsupported fashion. What's deployed already is out there so there's not a lot to do about that, but the docs should be accurate for both future and existing users.

Just changing
> Both LND and c-lightning support pruning. It's not possible to use pruning with Eclair.

to something like:

> c-lightning supports pruning. Both LND and Eclair do not support pruning at this time.

is all that's needed.

**Comment by britttttk** [comment]
nack - need more information and/or update reckless warning for LND and this FAQ

Open an issue in the btcpayserver-docker repository, to discuss with developers changes to LND with btcpayserver. The documentation should not give conflicting information to users.

**Comment by gkrizek** [comment]
@britttttk I agree issues with the btcpayserver-docker repo need to be addressed there.

I'm not sure I follow your recommendation for btcpayserver-docs. What would you like to see happen?

**Comment by britttttk** [comment]
I would understand: 
> Eclair does not support pruning. LND can be enabled with pruning but it is [not officially supported](https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#pruned-bitcoind-node). 

The documentation repository is not the appropriate place to discuss the viability of how btcpay works with LND. Need more info about how this affects btcpay deployments specifically from a technical perspective and if the CPU usage is related, it makes no mention of that in the document. 

The documentation should help to reduce the amount of questions received in the support chats and this does not provide clear information as to 1) why it's allowed in btcpay if it's not supported

**Comment by pavlenex** [comment]
That was my point. It seems that with doc fix, it's suggested that we clean our hands if something goes wrong and claim "We told you so" which is not the approach I personally like. If LND does not want to support pruning, the only logical step is to disable it entirely LND if pruning is enabled. It should be noted that a wide-majority of BTCPay instances runs pruned noes.

**Comment by Roasbeef** [comment]
> So what do you suggest? 99% of btcpay instances use pruned nodes

Very early on in both the development of lnd and btcpay, we repeatedly flagged that pruned mode wasn't supported. Unfortunately, I think the goal of giving users a cheap way to host BTCPay was prioritized over ensuring that users can use the system securely (a similar instance of this is when btcpay didn't give lnd users their seeds). It seems that with the default prune parameters, many users will start to run into these issues. Additionally, there're security issues here as well, which is why flagged this very on and our docs state to not use a pruned node.

**Comment by Roasbeef** [comment]
> it's suggested that we clean our hands if something goes wrong and claim "We told you so" which is not the approach I personally like. If LND does not want to support pruning, the only logical step is to disable LND if pruning is enabled. 

I think this would be really unfortunate. It's less about "we told you so", and more about ensuring your users default to a _safe_ configuration. We simply don't have what we need in `bitcoind` to do things securely at this point. There're other short cuts that may be viable, but we'd rather do things properly in the end. When `lnd` was even first integrated into BTCPay I flagged the dangers here with Dorier several times.

**Comment by britttttk** [comment]
@Roasbeef I will update the FAQ as mentioned [here](https://github.com/btcpayserver/btcpayserver-doc/issues/716#issuecomment-693180698). The documentation repository of btcpay serves to explain what is possible in btcpay. If you wish to remove LND from btcpay when pruning is enabled, open an issue in the respective repository or I can do it for you if you are unable to do that.

**Comment by Roasbeef** [comment]
Gotcha, yeah I think the convo started w.r.t just documentation, but then sprawled a bit. 

Given we're all already here: is it not possible to have those using the default docker set up _not_ use `bitcoind` in a pruned format when running against `lnd`. If y'all want to just disable things for now then I understand though that would be unfortunate. 

I think the bigger issue here is that the existing set of users may be exposed to resulting security issues due to `lnd` not properly having access to block in order to detect things like channel closures or other related scenarios.

**Comment by NicolasDorier** [comment]
> What size did you use, @pavlenex? I'm really surprised you never ran into issues. Are you sure you don't see strange errors and/or high load on your system?

In BTCPay Server, I would say 95% of people use pruning, and on those 95%, probably 80% use LND.
Aside of occasional CPU spikes, since merchants don't really need to route payments (they rarely send), this worked quite well in practice.

I think we warn already about Lightning Network in general being reckless when the merchant setup the store.

![image](https://user-images.githubusercontent.com/3020646/94011476-6066af80-fde2-11ea-9797-88d6eb500626.png)

That said, I agree the doc should be updated to reflect what LND officially support.

**Comment by AryanJ-NYC** [comment]
Given that LND does not support pruning, is it in a LND user's best interest to reindex the entire bitcoin blockchain and turn off pruning then? I'm suffering from sporadic high CPU usage (sometimes when there's almost zero traffic) on an AWS EC2 t2.medium running LND using `opt-save-storage-s` pruning.

**Comment by britttttk** [comment]
>Given that LND does not support pruning, is it in a LND user's best interest to reindex the entire bitcoin blockchain and turn off pruning then? I'm suffering from sporadic high CPU usage (sometimes when there's almost zero traffic) on an AWS EC2 t2.medium running LND using opt-save-storage-s pruning.

Please open an issue in the [Docker Repository ](https://github.com/btcpayserver/btcpayserver-docker) if you would like to discuss issues you are having with Pruning + LND + Docker. Look at how Eclair fragment as an example for how to do it.
