### ISSUE TITLE
Local development: broken link to 'Edit this page'

### ISSUE THREAD

**Issue by l33d4n** [btcpayserver/btcpayserver-doc#787]
Page URL: https://docs.btcpayserver.org/LocalDevelopment/

![image](https://user-images.githubusercontent.com/8020386/100714310-8f0b9280-33f0-11eb-9de2-5bcc79052ff3.png)

**Comment by pavlenex** [comment]
Weird, can replicate, indeed a bug.

@dennisreimann any idea why this might happen?

**Comment by dennisreimann** [comment]
That page get's assembled by using the [LocalDev](https://github.com/btcpayserver/btcpayserver-doc/edit/master/docs/LocalDev.md) page as a basis and [adding the info from the Tests README](https://github.com/btcpayserver/btcpayserver-doc/blob/master/setup-deps.sh#L35) at the end. 

For pages from external repos we [hide the edit links](https://github.com/btcpayserver/btcpayserver-doc/blob/master/setup-deps.sh#L18) as VuePress has no way to point to a specific URL via the [`editLink` property](https://vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links).

I'd suggest we hide it on that page too and propose a PR in VuePress, to allow for specifying edit page URLs, so that we can improve this if VuePress would like to merge something like this.
