### ISSUE TITLE
Improve Support

### ISSUE THREAD

**Issue by dylan696969** [btcpayserver/btcpayserver-doc#797]
I could not find the information I was looking for on the "Support" page (`/Support/`).

There is no option to import a new wallet I only have 3 options: import from: a hardware wallet, a wallet file or a QR code. i need the option for a new wallet?

**Comment by pavlenex** [comment]
This is explained in the https://docs.btcpayserver.org/CreateWallet/.
Added yellow warning box to make it more obvious in [b92e369](https://github.com/btcpayserver/btcpayserver-doc/commit/b92e369d9a6aa129dd12e37f9830f853e65c1a36)

**Comment by dylan696969** [comment]
Thanks for the reply. So the warning box tells me "If you are using a third-party host, this option needs to be explicitly enabled by the server admin. Generating a new wallet in an environment you are not sure is trustworthy, is discouraged."

Could you translate this for me? Where is this setting enabled? Do you mean our server host admin? I trust them but do I really have to involve them? Thanks again I appreciate your patience with a beginner

**Comment by dylan696969** [comment]
Lol someone liked the response as if you helped me with something. no help whatsoever. The yellow warning should say "this is not possible, delete BTCPay plugin" which is what I've done. Thanks for nothing.

**Comment by britttttk** [comment]
hey @dylan696969 sorry if the info provided did not clarify your question. Thanks for opening the issue. Here is some more info:

> There is no option to import a new wallet I only have 3 options: import from: a hardware wallet, a wallet file or a QR code. i need the option for a new wallet? There is no option to import a new wallet I only have 3 options:

If you only see 3 options, I am under the impression you are using a [third-party btcpay host](https://docs.btcpayserver.org/ThirdPartyHosting/) meaning you registered to use someone else's server.

> So the warning box tells me "If you are using a third-party host, this option needs to be explicitly enabled by the server admin. Generating a new wallet in an environment you are not sure is trustworthy, is discouraged."

The option you are looking for, [Hot Wallet](https://docs.btcpayserver.org/HotWallet/), you can see an image in the Hot Wallet doc showing where the admin can enable this setting. 

>Where is this setting enabled? 

It is enabled in the [server settings](https://docs.btcpayserver.org/Walkthrough/#server-settings). 

>Do you mean our server host admin? I trust them but do I really have to involve them? Thanks again I appreciate your patience with a beginner.

Yes, the server settings page is only available for admin access. If you do not see the SERVER SETTINGS button in your top nav, then you can't access it. 

There are [trust concerns for third-party hosts](https://docs.btcpayserver.org/ThirdPartyHosting/#trust-concerns) to allow users to create hot wallets on their server. This is related to why it is not enabled by default.

Your issue was closed because all of this information is already included in the documentation as you can see from above. Which takes time to locate on your behalf. However, you can ask for clarification regardless if the issue is open or closed. 

Thanks for opening the issue, this is how we create the [FAQ section questions](https://docs.btcpayserver.org/FAQ/).
