### ISSUE TITLE
Need doc of shopware plugin

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver-doc#800]
https://twitter.com/BtcpayServer/status/1338472173262917632?s=20

**Comment by pavlenex** [comment]
Good idea. @dennisreimann can we build docs from external repos out of our organizations or should we create doc ourselves?

**Comment by dennisreimann** [comment]
As long as the docs are public and their authors want us to include them we're good to go 😎

**Comment by pavlenex** [comment]
Awesome. @NicolasDorier should we try to incldue this as a part of btcpay organization, or should I try to get in touch with the authors for their permission to add it to our documentation? We want to build docs automatically from their docs readme.

**Comment by NicolasDorier** [comment]
Whichever is fine.

**Comment by pavlenex** [comment]
Their readme includes mention of the BitPay and has some sponsors I'm not sure if that's suitable for our docs as it may be misinterpreted as the foundation supporters.

Pinging @britttttk and @Zaxounette to audit what's the best course of action and what needs to be changed in the readme so it's acceptable to be included in our docs. (I'm fine with supporters as long as it's distinguished properly from foundation)

https://github.com/lampsolutions/LampSBtcPayShopware

So we do one of these:
1. Create our own doc
2. Audit their readme and improve it and include it in the automatic build

We can also contact the author to see if we can make this as a part of our organization.

**Comment by Zaxounette** [comment]
I would be fine with just linking to that doc, instead of integrating it of copying it into our own docs.

My view is that numerous entities (people or companies) will be creating stuff on top of BTCPay. Integrations, full A to Z payment rails using XYZ asset, plugins.
We definitly won't document each and every one. 
The best approche IMHO would again be, simply to document in-house developed features/plugins and merely link to outside made docs.
