### ISSUE TITLE
XMR/Monero Setup Documentation

### ISSUE THREAD

**Issue by 88plug** [btcpayserver/btcpayserver-doc#815]
Hi guys,
I would love to help support the project and found that the documentation for setting up XMR is very bad for new users.  There is no indication that a wallet file must be created or how to do it - and the steps to link that wallet file inside of BPS.  I will post shortly the basic steps I used, but it's misleading to think that just adding export BTCPAYGEN_CRYPTO2="xmr" will get things going without explaining the additional steps required.  Ideally I would like to do a pull request on the Readme and also update the docs.

Step 1: Add ```export BTCPAYGEN_CRYPTO2="xmr"``` and restart BPS to setup.
Step 2: Create a wallet :
```
docker exec -it btcpayserver_monerod monero-wallet-cli
```
Step 3: Copy the wallet out of the container to a safe location!

```
docker cp btcpayserver_monerod:/usr/local/bin/YOURWALLET /home/yourusername/
docker cp btcpayserver_monerod:/usr/local/bin/YOURWALLET.keys /home/yourusername/
```
Step 4: Add a Store to your installation if not already done
Step 5: In settings of the store you will see Monero in the menu now
Step 6: Upload your wallet file, keys, and insert your password.  
Step 7: Click "Enable"
Step 8: Verify all looks good, you should now see 
```
    Node available: True
    Wallet available: True (Wallet file present)
    Last updated: 1/12/2021 9:25:21 PM
    Synced: True (2273169 / 2273169)
```

It took me a few hours to button up this process, it would be great if it could be as easy as adding the other wallets!

**Comment by pavlenex** [comment]
@88plug Cool, feel free to add this in FAQ-Altcoins.md and in FAQ-Readme.md. Since this this issue is doc related, transferring it to adequate repo.

**Comment by Zaxounette** [comment]
After some thought, adding this directly to the docs will create a precedent and we would be somewhat obliged to add other altcoin setup/deployment tutorials and docs.

Currently in the [Altcoin FAQ list](https://docs.btcpayserver.org/FAQ/FAQ-Altcoin/#which-coins-does-btcpay-server-support) we link to a first issue also relating to XMR deployment.
Will add the link to this issue over there for continued discussion among XMR community members.

Also, in an upcoming PR, i will add wording stating that setup/deployment instructions may differ depending on the Altcoin.

**Comment by Librechain** [comment]
Absolutely ridiculous the policy that you idiots are coming up with here when it comes to "altcoins". You're poison to this space, you intellectual nazis.

**Comment by britttttk** [comment]
@Zaxounette altcoin community can document their build. It's more that the btcpay contributors are not required to do it.

**Comment by britttttk** [comment]
@Librechain the issue was closed due to the discussion we had in our recent docs org meeting regarding the recent altcoin questions that have come up here and in the chat. The consensus of that discussion was that we need to direct users' questions to the community, or that community should document the altcoin build. 

Your issue was closed as a result of that discussion as it's related to the REQUEST of altcoin docs. You are of course allowed to document this process you have outlined here in the Altcoins FAQ as @pavlenex mentioned. However issues are closed for inactivity.

**Comment by Kukks** [comment]
> Absolutely ridiculous the policy that you idiots are coming up with here when it comes to "altcoins". You're poison to this space, you intellectual nazis.

Be the change you want to see in the world @Librechain. If you want docs, write the docs yourself instead of insulting hardworking contributors. Your attitude does not help your case in any way.

**Comment by ftpmorph** [comment]
> Absolutely ridiculous the policy that you idiots are coming up with here when it comes to "altcoins". You're poison to this space, you intellectual nazis.

Seems a bit harsh to call a group of volunteers who have created an excellent self-hosted crypto payment platform "idiots", "poison", and "nazis" just because they don't document altcoins as well as BTC.

This is coming from someone who supports and is invested in multiple altcoins myself, btw.

Do you really think you'll move in any constructive direction if you speak like this to devs of open source projects who work for free? I mean shit even if I was getting paid and my boss talked to me like that I'd be looking for a new job.

Calm down. The support for many altcoins is there. Documentation is lacking in some areas because altcoin support was developed by the community. So it's not even the fault of the BTCPay devs in the first place.

And if you want better documentation... do what @Kukks said and write better documentation instead of calling people poisonous nazis because they don't happen to prioritise your favourite altcoin in a project that explicitly states it's aimed at bitcoin payments.

**Comment by b4sh1t1** [comment]
when choice language it's crash !
Error: failed to generate new wallet: failed to save file "XMR.keys"

any suggestion guys ?

**Comment by ksdhans** [comment]
Just a quick note for those who want to use a Ledger hardware wallet for Monero:
Extracting the view-only key is a bit challenging, but is documented here: 
https://shawnhogan.com/2021/07/how-to-get-monero-private-view-key-from-ledger.html
You'll need to get ledgerctl from here: https://github.com/LedgerHQ/ledgerctl

Hopefully the Monero team will make this easier at some point.

**Comment by max-privacypractical** [comment]
> when choice language it's crash !
> 
> `Error: failed to generate new wallet: failed to save file "XMR.keys"`

Solution to this is to run as root using the below

`docker exec -u root -it btcpayserver_monerod monero-wallet-cli`

**Comment by valsha** [comment]
Hi, is possible to run Monero in this scenario with Hardware wallets? Like LEdger oar any other wallets. Thank you for your help.
