### ISSUE TITLE
SMTP settings for local POSTFIX server

### ISSUE THREAD

**Issue by mpuz** [btcpayserver/btcpayserver-doc#861]
Please add some info on  what settings to use for local Postfix SMTP server. It sends mails from ssh CLI using letsencrypt certs but I have no idea what settings to use inside btcpay server config so it can use Postfix to send emails.
Please help! Thank You!

**Comment by Zaxounette** [comment]
Hi @mpuz !

Every single e-mail provider has different settings to enable, input or otherwise configure.
We are unable to provide you with the exact settings you need for your specific provider.

Please see the docs related to this [here](https://docs.btcpayserver.org/FAQ/FAQ-ServerSettings/#how-to-configure-smtp-settings-in-btcpay) for an **example** using gmail.

**Comment by mpuz** [comment]
Postfix is not an email provider but SMTP server software used for sending emails widely.

**Comment by Zaxounette** [comment]
Oh okay I think I get it.

The SMTP configs ask for a domain, but since you're in local, you don't have any for the configs.

Pinging @Kukks .

**Comment by Kukks** [comment]
> Oh okay I think I get it.
> 
> The SMTP configs ask for a domain, but since you're in local, you don't have any for the configs.
> 
> Pinging @Kukks .

There is still a hostname that postfix is reachable at. We cannot provide you with your own details of your setup. :)  

BTCPay asks for a an SMTP server hostname +credentials.

**Comment by mpuz** [comment]
Docker uses its own network, what i need is to access postfix on localhost in which case it does not need authentication at all.. Should i run postfix in another container sharing same network with btcpay one?
