### ISSUE TITLE
Updates to wallet provider documentation

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#881]
Relates to #837 

Need to make sure all the wallet provider docs we have are also updated with the new wallet ui redesigns. 
Examples: Cold Card, Electrum, Wasabi, etc.

https://docs.btcpayserver.org/ColdCardWallet/#connecting-coldcard-wallet-to-btcpay-server
Maybe could use new videos if someone is feeling up to it :)

**Comment by britttttk** [comment]
I started working on this update and Electrum doc is showing to connect using xpub. 
I think our new recommended way is to export the wallet file. Do you agree @Zaxounette?

**Comment by Zaxounette** [comment]
It's gonna be tricky recommending import file for electrum.

On the one side it's a positive because the file also contains the path info, so users will not be confused as to where their funds are and all.
But in the same time the import requires that the file not be protected by a passphrase AFAIR. Not really a positive feeling security wise.
Or am I missing something ?

**Comment by britttttk** [comment]
They can unencrypt and and then re-encrypt in electrum while doing the export :/ @Zaxounette

**Comment by Zaxounette** [comment]
> They can unencrypt and and then re-encrypt in electrum while doing the export :/ @Zaxounette

Oh, then never mind what I said then.
Import file is better to recommend in that case !

**Comment by britttttk** [comment]
>Import file is better to recommend 

ok thanks i'll update it to use that way then
